#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
LIGHTGREEN='\033[1;32m'
###dshfkdsjhf

branch=$(git symbolic-ref HEAD)
echo "$branch - branch"

echo "$GIT_AUTHOR_NAME - Author name"
echo "$GIT_COMMITTER_NAME - Committer name"
echo "$GIT_COMMITTER_EMAIL - Committer email"
echo "$GIT_AUTHOR_DATE - GIT_AUTHOR_DATE"
echo "$GIT_AUTHOR_EMAIL - GIT_AUTHOR_EMAIL"
echo "$GIT_COMMITTER_DATE - GIT_COMMITTER_DATE"
echo "$GIT_TRACE - GIT_TRACE"
echo "$GIT_TRACE_PACK_ACCESS - GIT_TRACE_PACK_ACCESS"
echo "$GIT_TRACE_PACKET - GIT_TRACE_PACKET"
echo "$GIT_EXEC_PATH - GIT_EXEC_PATH"
echo "$HOME - HOME"
echo "$PREFIX - PREFIX"
echo "$GIT_CONFIG_NOSYSTEM - GIT_CONFIG_NOSYSTEM"
echo "$GIT_PAGER - GIT_PAGER"
echo "$GIT_EDITOR - GIT_EDITOR"
echo "$GIT_DIR - GIT_DIR"
echo "$GIT_CEILING_DIRECTORIES - GIT_CEILING_DIRECTORIES"
echo "$GIT_WORK_TREE - GIT_WORK_TREE"
echo "$GIT_INDEX_FILE - GIT_INDEX_FILE"
echo "$GIT_OBJECT_DIRECTORY - GIT_OBJECT_DIRECTORY"
echo "$GIT_GLOB_PATHSPECS - GIT_GLOB_PATHSPECS"

msg="$(grep -v '^#' $1)" 
echo "$msg - commit message"
authors_whitelist=("Lee Jones" "Senik Hakobyan")
MESSAGE_PATTERNS=(
  "^GRP\-[0-9]+[[:blank:]](FIX|CHANGE|HOTFIX|FEATURE){1}[[:blank:]](CORE|SHARED|ADM|CSR|BUS|OTHER){1}[[:blank:]]-[[:blank:]]\([[:alnum:]./\-]+\)[[:blank:]]:[[:blank:]]([[:alnum:],.\-]+[[:blank:]]?){10,}$"
  "^GRP\-[0-9]+[[:blank:]](FIX|CHANGE|HOTFIX|FEATURE){1}[[:blank:]](CORE|SHARED|ADM|CSR|BUS|OTHER){1}[[:blank:]]-[[:blank:]]([[:alnum:],.\-]+[[:blank:]]?){10,}$" 
)

if [[ "${authors_whitelist[*]}" =~ ${GIT_AUTHOR_NAME} ]]; then
  exit 0
fi

for i in ${MESSAGE_PATTERNS[@]}
do
  : 
    if [[ "${msg}" =~ $i ]]; then
      exit 0
    fi 
done

echo "${RED}Please provide valid commit message${RED}"
echo "Our standard commit message pattern is ${GREEN}GRP-CARD_NUMBER FIX|CHANGE|HOTFIX|FEATURE CORE|SHARED|ADM|CSR|BUS|OTHER - (File location[not required]) : Commit description${GREEN}\n"
echo "${BLUE}Some valid examples here:${BLUE}\n"
echo "${LIGHTGREEN}GRP-0888 CHANGE BUS - Change styles in dashboard ${LIGHTGREEN}"
echo "${LIGHTGREEN}GRP-0888 HOTFIX CORE - Fix checkbox unchecking issue ${LIGHTGREEN}"
echo "${LIGHTGREEN}GRP-0888 FIX OTHER - (jest.config.js) Fix testMatch option issue ${LIGHTGREEN}"
echo "${LIGHTGREEN}GRP-0888 CHANGE BUS - (pages/dashboard) : Change styles ${LIGHTGREEN}"
echo "${LIGHTGREEN}GRP-0888 HOTFIX CORE - (components/checkbox) : Fix checkbox unchecking issue ${LIGHTGREEN}\n"

echo "${RED}Commit description should contain at least 10 alphanumeric characters separated by a single space:${RED}\n"
exit 1
